# Generated by Django 3.2.13 on 2023-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='Open', max_length=6),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='Low', max_length=8),
        ),
    ]
