# Generated by Django 3.2.13 on 2023-03-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
