# Generated by Django 3.2.13 on 2023-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20230222_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
