# Generated by Django 3.2.13 on 2023-02-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20230223_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_on', 'title')},
        ),
    ]
