# Generated by Django 3.2.13 on 2023-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=1024),
        ),
    ]
