# Generated by Django 3.2.13 on 2023-02-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set(),
        ),
    ]
