# Generated by Django 3.2.13 on 2023-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_issue_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('issue_status', 'priority', '-created_on', '-visits')},
        ),
    ]
