# Generated by Django 3.2.13 on 2023-03-09 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0010_auto_20230224_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_users',
            field=models.ManyToManyField(related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
