# Generated by Django 3.2.13 on 2023-03-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20230309_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-visits', '-created_on', 'issue_status', 'priority')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-visits', '-created_on', 'title')},
        ),
    ]
